export const APP_ROUTES = {
  login: '/login',
  app: '/app',
  dashboard: '/app/dashboard',
  brands: '/app/brands',
  categories: '/app/categories',
  products: '/app/products',
  product_new: '/app/products/new',
  product_edit: (id: string) => `/app/products/${id}/edit`,
  product_variants: (id: string) => `/app/products/${id}/variants`,
  suppliers: '/app/suppliers',
  stock_in: '/app/stock-in',
  stock_in_new: '/app/stock-in/new',
  stock_in_detail: (id: string) => `/app/stock-in/${id}`,
  pos: '/app/pos',
  sales: '/app/sales',
  sale_detail: (id: string) => `/app/sales/${id}`,
  customers: '/app/customers',
  reports_daily_sales: '/app/reports/daily-sales',
  reports_monthly_sales: '/app/reports/monthly-sales',
  reports_stock_balance: '/app/reports/stock-balance',
  reports_low_stock: '/app/reports/low-stock',
  reports_best_selling: '/app/reports/best-selling',
  reports_profit: '/app/reports/profit',
  settings_shop: '/app/settings/shop',
  settings_users: '/app/settings/users',
} as const;
